server {
	client_max_body_size 40M;
	server_name dev.migratis.com;
	root /var/www/migratis/frontend/build;
	index index.html index.htm;

	location / {
		try_files $uri $uri/ /index.html?q=$uri&$args;
 		access_log /var/log/nginx/migratis.access.log;
		error_log /var/log/nginx/migratis.error.log;
	}
    
    location = /favicon.ico { access_log off; log_not_found off; }
    location /assets/ {
        root /var/www/migratis/backend;
    }

    location /backend/ {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass http://172.21.0.3:8002;
        proxy_set_header X-Forwarded-Proto $scheme;
        access_log /var/log/nginx/dev.api.migratis.com.access.log;
        error_log /var/log/nginx/dev.api.migratis.com.error.log;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dev.migratis.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dev.migratis.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = dev.migratis.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	server_name dev.migratis.com;
    listen 80;
    return 404; # managed by Certbot
}
