# Generated by Django 6.0.7 on 2026-07-21 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=30, unique=True)),
                ('credits', models.PositiveIntegerField(default=1, help_text='Number of credits deducted per operation')),
            ],
            options={
                'verbose_name': 'Credit cost',
                'verbose_name_plural': 'Credit costs',
                'db_table': 'credits_creditcost',
                'ordering': ['operation'],
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credits', models.IntegerField(default=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit balance',
                'verbose_name_plural': 'Credit balances',
                'db_table': 'credits_creditbalance',
            },
        ),
    ]
