"""
Django settings for migratis project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# env('…') returns the raw string, so 'False' would be truthy and leave DEBUG on
# in production. Parse as a real boolean. (Same fix applied to the *_SECURE flags.)
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

STATIC_ROOT = 'assets/'
STATIC_URL = '/assets/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR
MEDIA_FULL_URL = env('MEDIA_FULL_URL', default='')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# Application definition

USE_SQLITE = env.bool('USE_SQLITE', default=False)

INSTALLED_APPS = [
    'clearcache',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_crontab',
    'ninja',
    'corsheaders',
    'colorfield',
    'migratis.api.apps.ApiConfig',
    'import_export',
    'migratis.installer.apps.InstallerConfig',
    # ── Activated by generated app settings_patch.py ──────────────────────
    # 'migratis.user.apps.UserConfig',
    # 'migratis.i18n.apps.I18NConfig',
    # 'migratis.cookie.apps.CookieConfig',
    # 'migratis.support.apps.SupportConfig',
    # 'migratis.subscription.apps.SubscriptionConfig',
    # 'migratis.stripe_payment.apps.StripePaymentConfig',
    # 'migratis.credits.apps.CreditsConfig',
]

# django.contrib.postgres requires a live PostgreSQL backend — exclude for SQLite.
if not USE_SQLITE:
    INSTALLED_APPS.insert(7, 'django.contrib.postgres')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'ninja.compatibility.files.fix_request_files_middleware',
]

ROOT_URLCONF = 'migratis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# AUTH_USER_MODEL = 'user.User'  # Uncommented by generated app settings_patch.py

WSGI_APPLICATION = 'migratis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='172.21.0.2'),
            'PORT': env('DB_PORT'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True    
CORS_ORIGIN_WHITELIST = env.list('CORS_ORIGIN_WHITELIST')
CORS_ALLOW_HEADERS = [
    "X-CSRFToken",
    "Content-Type",
    "Accept",
    "Authorization",
]

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')

# NOTE: env('…') returns the raw string, so 'False' is truthy and would force
# the Secure flag on even in local HTTP dev — which stops the session cookie from
# round-tripping (every request gets a fresh session, losing the installer's
# remembered-2FA trust and the login session). Parse as a real boolean instead.
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)

SECURE_BROWSER_XSS_FILTER = True

CSRF_COOKIE_SAMESITE = 'strict' #was strict
SESSION_COOKIE_SAMESITE = 'strict' #was strict

CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 14400

SITE_NAME = 'Simple Projection'

FRONTEND_URL = env('FRONTEND_URL')
BACKEND_URL = env('BACKEND_URL')

EMAIL_USE_TLS = True
# SMTP credentials serve one of three transports (see below), so they carry
# defaults: a fresh checkout has no mail account and must still boot.
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT = 587
# Only governs the SMTP path below. Django defaults it to None, which hands
# smtplib a blocking socket: an unreachable mail host then stalls on the OS TCP
# timeout (~130s). Mail is sent inline on request paths — sendTFA() runs inside
# POST /user/login — so an unbounded wait there is an unbounded request, and a
# proxy in front returns 504 long before Python gives up.
EMAIL_TIMEOUT = 10

# --------------------------------------------------------------------------- #
# Outbound mail transport
#
# Some hosts' providers drop outbound SMTP wholesale — on the migratis.ai box
# 587, 465 and 2525 all time out while port 22 to the same mail server answers
# in 0.11s and a third-party probe gets Postfix's banner. Nothing is wrong with
# the mail server; mail simply cannot leave over SMTP. Mailjet's HTTPS Send API
# goes out over 443, which is the one path that does work.
#
# Anymail keeps Django's EmailMessage API, so every existing call site
# (sendTFA, password reset, invitations, support) is untouched.
#
# Three transports, chosen by what the .env actually carries:
#   both MAILJET_* keys  → Mailjet's HTTPS Send API (or any Anymail provider)
#   EMAIL_HOST set       → plain SMTP, no third party involved
#   neither              → the console backend, which prints the mail to the
#                          container log instead of sending it
# The console fallback is what makes a fresh checkout work with no mail account
# at all: nothing raises, nothing hangs on a dead SMTP socket, and the message —
# TFA code, reset link — is readable in `docker logs`. Tests are unaffected
# either way: Django's test runner swaps in the locmem backend.
# --------------------------------------------------------------------------- #
MAILJET_API_KEY = env('MAILJET_API_KEY', default='')
MAILJET_SECRET_KEY = env('MAILJET_SECRET_KEY', default='')

if MAILJET_API_KEY and MAILJET_SECRET_KEY:
    EMAIL_BACKEND = 'anymail.backends.mailjet.EmailBackend'
    ANYMAIL = {
        'MAILJET_API_KEY': MAILJET_API_KEY,
        'MAILJET_SECRET_KEY': MAILJET_SECRET_KEY,
        # EMAIL_TIMEOUT does not reach this backend — it is an SMTP setting.
        # Without this, an unresponsive api.mailjet.com would hang a login for
        # anymail's 30s default: the same unbounded wait inside a request that
        # the SMTP timeout above exists to prevent, just over 443.
        'REQUESTS_TIMEOUT': 10,
    }
elif EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

FILE_UPLOAD_HANDLERS = (
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
)

MIGRATIS_BACKEND_URL = env('MIGRATIS_BACKEND_URL', default='http://host.docker.internal:8000')

# Who receives Django's unhandled-exception mail. Django's own AdminEmailHandler
# (on the `django.request` logger) is the only reader — a 500 with DEBUG=False
# mails the traceback here. Empty disables it. Format: "Name <addr>, Name <addr>".
ADMINS = [
    (entry.split('<')[0].strip(), entry.split('<')[-1].rstrip('>').strip())
    for entry in env.list('ADMINS', default=[])
]
# The From: address on every outbound mail. Under an API transport it must be a
# sender the provider has validated, or the send is rejected.
EMAIL_SENDER = env('EMAIL_SENDER', default='')
STRIPE_API_KEY  = env('STRIPE_API_KEY')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET_KEY = env('STRIPE_WEBHOOK_SECRET_KEY')

# ── credits (migratis.credits) ─────────────────────────────────────────────
# Read by the credits app when activated. Harmless when inactive.
CREDITS_FREE_TIER_LIMIT = 10  # free credits per user
CREDIT_TIERS = [
    {'max_calls': 20, 'extra_amount': 20, 'price': '9.99'},
    {'max_calls': 100, 'extra_amount': 50, 'price': '19.99'},
    {'max_calls': None, 'extra_amount': 100, 'price': '29.99'},
]
CREDITS_CURRENCY = 'eur'

# ── Road routing (optional `routing` module) ────────────────────────────────────
# A self-hosted routing engine that has ingested the OSM road network. Empty URL
# = the feature is off: `geo` fields in route mode keep working and the traced
# line is stored exactly as drawn, with no error anywhere.
#
# Installing the module cannot start the engine — the installer has no Docker
# socket and must not be given one. The operator brings the service up by hand
# (`docker compose --profile routing up -d`) and points this at it; the install
# response says so with `routing_service_required`.
#
# **Your application routes against your engine, and calls nobody else.** The
# design sandbox at migratis.ai is the other world: it has no tile set of its
# own and calls an external service (openrouteservice) so that a `route` field
# can be *tried* before it is shipped. Neither ever calls the other, and no end
# user of this application has coordinates sent anywhere — including to Migratis
# (SCOPE_routing_sandbox_external.md D3′/§4).
#
# The adapter for that external service ships in `routing/engines.py` because
# the module is one codebase in both places. It is inert here: `ors` is not
# selected below, and even if it were it would need an API key of yours before
# it did anything. Set `ROUTING_ENGINE=ors` + `ROUTING_ENGINE_KEY=…` only if you
# would rather rent an engine than run one.
ROUTING_ENGINE     = env('ROUTING_ENGINE', default='valhalla')
ROUTING_ENGINE_URL = env('ROUTING_ENGINE_URL', default='')
ROUTING_ENGINE_KEY = env('ROUTING_ENGINE_KEY', default='')
ROUTING_ENGINE_TIMEOUT = int(env('ROUTING_ENGINE_TIMEOUT', default='20'))

# **`POST /routing/snap` stays open here, and is gated on migratis.ai.** That is
# the one place the two deployments deliberately disagree, and it is a setting
# rather than a fork of the code (SCOPE_routing_sandbox_external.md §6).
#
# The reasoning that opened the endpoint still holds in an installed app: a
# generated app may let an anonymous role create records, so a login-gated snap
# would mean the map editor works for the owner and silently draws straight
# lines for everyone else. The engine being called is yours, free and stateless,
# so there is no quota for a stranger to exhaust — and the exposure stays bounded
# the way it always was: the engine URL comes from here and never from a request
# (no SSRF), waypoints are capped and range-checked before any network call,
# nothing is written and nothing is charged.
#
# On migratis.ai neither of those is true any more: a generated app calls its own
# engine now, so the only legitimate caller of that copy is its own sandbox, and
# that copy stands in front of somebody else's metered quota. It names an
# authorizer here and sets a per-caller ceiling; this file names neither, and the
# endpoint behaves exactly as it did before that scope.
ROUTING_SNAP_AUTHORIZER = env('ROUTING_SNAP_AUTHORIZER', default='')
ROUTING_SNAP_RATE_PER_MINUTE = int(env('ROUTING_SNAP_RATE_PER_MINUTE', default='0'))

CRONJOBS = []

# Subscription gate — False means check_access() enforces subscription
NO_SUBSCRIPTION = env.bool('NO_SUBSCRIPTION', default=False)

# Path to the frontend src/ directory as seen from inside the container.
# Mount the frontend volume in docker-compose for the installer to write files automatically.
FRONTEND_SRC_DIR = env('FRONTEND_SRC_DIR', default='/frontend/src')

# Installer gate — when False, the /installer/ API is not mounted at all.
# Keep in sync with INSTALLER in frontend/src/settings.js (which hides the route).
INSTALLER = env.bool('INSTALLER', default=True)




INSTALLED_APPS += ['migratis.i18n.apps.I18NConfig']
INSTALLED_APPS += ['migratis.cookie.apps.CookieConfig']

# ── i18n ─────────────────────────────────────────────────────────────────
LANGUAGE_CODE = 'fr'
LANGUAGES = [('en', 'English'), ('fr', 'French'), ('pt', 'Portuguese'), ('zh', 'Chinese')]
LOCALE_PATHS = [BASE_DIR / 'locale']
USE_I18N = True

# ── Auto-load installed app settings patches ──────────────────────────────
import glob as _glob
for _patch in sorted(_glob.glob(str(BASE_DIR / 'settings_patches' / '*.py'))):
    if not _patch.endswith('__init__.py'):
        with open(_patch) as _fh:
            exec(compile(_fh.read(), _patch, 'exec'))
