"""
Django settings for migratis project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# env('…') returns the raw string, so 'False' would be truthy and leave DEBUG on
# in production. Parse as a real boolean. (Same fix applied to the *_SECURE flags.)
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

STATIC_ROOT = 'assets/'
STATIC_URL = '/assets/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR
MEDIA_FULL_URL = env('MEDIA_FULL_URL', default='')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# Application definition

USE_SQLITE = env.bool('USE_SQLITE', default=False)

INSTALLED_APPS = [
    'clearcache',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_crontab',
    'ninja',
    'corsheaders',
    'colorfield',
    'migratis.api.apps.ApiConfig',
    'import_export',
    'migratis.installer.apps.InstallerConfig',
    # ── Activated by generated app settings_patch.py ──────────────────────
    # 'migratis.user.apps.UserConfig',
    # 'migratis.i18n.apps.I18NConfig',
    # 'migratis.cookie.apps.CookieConfig',
    # 'migratis.support.apps.SupportConfig',
    # 'migratis.subscription.apps.SubscriptionConfig',
    # 'migratis.stripe_payment.apps.StripePaymentConfig',
    # 'migratis.credits.apps.CreditsConfig',
]

# django.contrib.postgres requires a live PostgreSQL backend — exclude for SQLite.
if not USE_SQLITE:
    INSTALLED_APPS.insert(7, 'django.contrib.postgres')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'ninja.compatibility.files.fix_request_files_middleware',
]

ROOT_URLCONF = 'migratis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# AUTH_USER_MODEL = 'user.User'  # Uncommented by generated app settings_patch.py

WSGI_APPLICATION = 'migratis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='172.21.0.2'),
            'PORT': env('DB_PORT'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True    
CORS_ORIGIN_WHITELIST = env.list('CORS_ORIGIN_WHITELIST')
CORS_ALLOW_HEADERS = [
    "X-CSRFToken",
    "Content-Type",
    "Accept",
    "Authorization",
]

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')

# NOTE: env('…') returns the raw string, so 'False' is truthy and would force
# the Secure flag on even in local HTTP dev — which stops the session cookie from
# round-tripping (every request gets a fresh session, losing the installer's
# remembered-2FA trust and the login session). Parse as a real boolean instead.
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)

SECURE_BROWSER_XSS_FILTER = True

CSRF_COOKIE_SAMESITE = 'strict' #was strict
SESSION_COOKIE_SAMESITE = 'strict' #was strict

CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 14400

SITE_NAME = 'Simple Projection'

FRONTEND_URL = env('FRONTEND_URL')
BACKEND_URL = env('BACKEND_URL')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 587
EMAIL_SENDER = env('EMAIL_SENDER')
EMAIL_MODERATOR = env('EMAIL_MODERATOR')

FILE_UPLOAD_HANDLERS = (
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
)

MIGRATIS_BACKEND_URL = env('MIGRATIS_BACKEND_URL', default='http://host.docker.internal:8000')

ADMINS          = env.list('ADMINS', default=[])
EMAIL_SENDER    = env('EMAIL_SENDER',    default='')
EMAIL_MODERATOR = env('EMAIL_MODERATOR', default='')
STRIPE_API_KEY  = env('STRIPE_API_KEY')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET_KEY = env('STRIPE_WEBHOOK_SECRET_KEY')

# ── credits (migratis.credits) ─────────────────────────────────────────────
# Read by the credits app when activated. Harmless when inactive.
CREDITS_FREE_TIER_LIMIT = 10  # free credits per user
CREDIT_TIERS = [
    {'max_calls': 20, 'extra_amount': 20, 'price': '9.99'},
    {'max_calls': 100, 'extra_amount': 50, 'price': '19.99'},
    {'max_calls': None, 'extra_amount': 100, 'price': '29.99'},
]
CREDITS_CURRENCY = 'eur'

CRONJOBS = []

# Subscription gate — False means check_access() enforces subscription
NO_SUBSCRIPTION = env.bool('NO_SUBSCRIPTION', default=False)

# Path to the frontend src/ directory as seen from inside the container.
# Mount the frontend volume in docker-compose for the installer to write files automatically.
FRONTEND_SRC_DIR = env('FRONTEND_SRC_DIR', default='/frontend/src')

# Installer gate — when False, the /installer/ API is not mounted at all.
# Keep in sync with INSTALLER in frontend/src/settings.js (which hides the route).
INSTALLER = env.bool('INSTALLER', default=True)




INSTALLED_APPS += ['migratis.i18n.apps.I18NConfig']
INSTALLED_APPS += ['migratis.cookie.apps.CookieConfig']

# ── i18n ─────────────────────────────────────────────────────────────────
LANGUAGE_CODE = 'fr'
LANGUAGES = [('en', 'English'), ('fr', 'French'), ('pt', 'Portuguese'), ('zh', 'Chinese')]
LOCALE_PATHS = [BASE_DIR / 'locale']
USE_I18N = True

# ── Auto-load installed app settings patches ──────────────────────────────
import glob as _glob
for _patch in sorted(_glob.glob(str(BASE_DIR / 'settings_patches' / '*.py'))):
    if not _patch.endswith('__init__.py'):
        with open(_patch) as _fh:
            exec(compile(_fh.read(), _patch, 'exec'))
