# Generated by Django 6.0.6 on 2026-07-20 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=64)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Processed Stripe events',
            },
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=32)),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stripe payments',
            },
        ),
    ]
