# Generated by Django 6.0.4 on 2026-04-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationNameSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Namespaces',
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('ns', models.ManyToManyField(related_name='key_name_spaces', to='i18n.translationnamespace')),
            ],
            options={
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.CreateModel(
            name='TranslationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ro', 'Română')], max_length=2)),
                ('text', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='i18n.translationkey')),
            ],
            options={
                'unique_together': {('key', 'lng')},
            },
        ),
    ]
