import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import { useShell } from '../shell/ShellContext';
import {
  IoCodeSlashOutline as CodeIcon,
  IoSparklesOutline as SparklesIcon,
  IoRocketOutline as RocketIcon,
  IoShieldCheckmarkOutline as ShieldIcon,
  IoGitNetworkOutline as NetworkIcon,
  IoGlobeOutline as GlobeIcon,
  IoBuildOutline as BuildIcon,
  IoLayersOutline as LayersIcon,
  IoCheckmarkCircleOutline as CheckIcon,
  IoHardwareChipOutline as ChipIcon,
  IoPeopleOutline as PeopleIcon,
  IoMapOutline as MapIcon,
  IoTerminalOutline as TerminalIcon,
} from 'react-icons/io5';

// Landing-page chapters, in narrative order: design → preview → generate →
// deploy. `key` prefixes the i18n keys (`<key>-title`, `-desc`, `-f1`..`-f4`)
// in the `home` namespace; the strings below are the English fallbacks used
// before the translation bundle has loaded. Sections alternate background and
// side automatically, so reordering this list is all it takes to reshuffle the
// page.
const CHAPTERS = [
  {
    key: 'ch1',
    Icon: SparklesIcon,
    title: 'AI-Powered Schema Design',
    desc: 'Describe your application in plain language and let the AI generate the complete data model with entities, fields, relationships, roles, and validation rules.',
    features: [
      'Natural language application descriptions',
      'Automatic entity and field generation',
      'Smart relationship detection',
      'Review every AI change before it is applied',
    ],
  },
  {
    key: 'ch9',
    Icon: ChipIcon,
    title: 'Choose Your AI Model',
    desc: 'Pick the model behind every AI call. OpenAI, Anthropic, Gemini, xAI, and DeepSeek are all available, each priced per call so you stay in control of the cost.',
    features: [
      'Five providers, one picker',
      'Per-call cost shown up front',
      'Per-account default model',
      'Pay-as-you-go credits, no lock-in',
    ],
  },
  {
    key: 'ch2',
    Icon: BuildIcon,
    title: 'Interactive Sandbox Testing',
    desc: 'Test your data model in a live sandbox environment before generating any code. Create, edit, and delete records to verify your schema works exactly as intended.',
    features: [
      'Real-time data model testing',
      'Search, filter, and sort records',
      'Multiple display modes (table, cards, kanban, gallery, map)',
      'Preview the app as any role or member',
    ],
  },
  {
    key: 'ch8',
    Icon: RocketIcon,
    title: 'Workflow Automation',
    desc: 'Define automated workflows that trigger actions based on events. Create, update, compute, and export data automatically with AI-guided logic.',
    features: [
      'Event-driven automation',
      'AI-assisted workflow design',
      'Branching steps with preconditions',
      'Per-step role gating',
    ],
  },
  {
    key: 'ch10',
    Icon: PeopleIcon,
    title: 'Roles, Permissions & Visibility',
    desc: 'Every application defines its own role ladder — public, member, moderator, whatever fits — and the platform enforces it consistently in the sandbox and in the generated code.',
    features: [
      'Per-application role ladder',
      'Read and write access per entity and field',
      'Row-level visibility rules',
      'Members only ever edit their own records',
    ],
  },
  {
    key: 'ch11',
    Icon: MapIcon,
    title: 'Maps & Location Data',
    desc: 'Give your application a sense of place. Location fields capture points, routes, and areas on an OpenStreetMap-backed map, ready to display and edit out of the box.',
    features: [
      'Points, itineraries, and areas',
      'Built-in map picker and viewer',
      'OpenStreetMap — no API key needed',
      'Map display mode for record lists',
    ],
  },
  {
    key: 'ch3',
    Icon: CodeIcon,
    title: 'One-Click Code Generation',
    desc: 'Generate production-ready Django backend and React frontend code from your validated schema. Everything you need to deploy your application.',
    features: [
      'Django models and APIs',
      'React components and forms',
      'Admin interface configuration',
      'Database migrations included',
    ],
  },
  {
    key: 'ch4',
    Icon: NetworkIcon,
    title: 'Public "base" Repository',
    desc: 'Migratis provides a public GitHub repository called "base" from which you can install any application generated by the platform. Your apps are ready to deploy in minutes.',
    features: [
      'Pre-configured Django project structure',
      'Ready-to-install application modules',
      'One-command deployment setup',
      'Re-generate and upgrade an installed app',
    ],
  },
  {
    key: 'ch5',
    Icon: GlobeIcon,
    title: 'Multi-Language Support',
    desc: 'Build applications that support multiple languages out of the box. Our AI generates translations for all your entities and fields.',
    features: [
      'Built-in i18n support',
      'AI-generated translations',
      '40+ languages supported',
      'Easy translation management',
    ],
  },
  {
    key: 'ch6',
    Icon: LayersIcon,
    title: 'Ready-Made Modules',
    desc: 'Accelerate development with pre-built modules for authentication, payments, internationalization, support tickets, and cookie consent.',
    features: [
      'User authentication & profiles',
      'Stripe subscriptions or metered credits',
      'GDPR cookie consent',
      'Customer support system',
    ],
  },
  {
    key: 'ch7',
    Icon: ShieldIcon,
    title: 'Security & Best Practices',
    desc: 'Your application follows security best practices with built-in protection against common vulnerabilities, role-based access control, and regular security updates.',
    features: [
      'SQL injection prevention',
      'CSRF protection included',
      'Role-based access control',
      'Secure password hashing',
    ],
  },
  {
    key: 'ch12',
    Icon: TerminalIcon,
    title: 'Bring Your Own AI Agent',
    desc: 'Everything the platform does is also a token-authenticated API. Point your own AI agent at it: the agent reads the live guide, declares the schema, workflow, and screens, and corrects itself against machine-readable rejections — no Migratis AI call ever fires on this lane.',
    features: [
      'Token-authenticated API, with an MCP wrapper',
      'Self-describing guide, schema, and vocabulary',
      'Machine-readable rejections to self-correct against',
      'Your agent builds the sandbox — only you approve it',
    ],
  },
];

const Chapter = ({ chapter, reversed, shaded, t }) => {
  const { key, Icon, title, desc, features } = chapter;

  return (
    <section className={`chapter-section py-5${shaded ? ' bg-light' : ''}`}>
      <div className="container">
        <div className={`row align-items-center${reversed ? ' flex-row-reverse' : ''}`}>
          <div className="col-md-6">
            <div className="chapter-icon">
              <Icon size={64} />
            </div>
            <h2 className="mb-3">{t(`${key}-title`, title)}</h2>
            <p className="lead">{t(`${key}-desc`, desc)}</p>
          </div>
          <div className="col-md-6">
            <ul className="feature-list list-unstyled">
              {features.map((feature, i) => (
                <li key={`${key}-f${i + 1}`}>
                  <CheckIcon className="me-2" /> {t(`${key}-f${i + 1}`, feature)}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
};

const Home = () => {
  const { useAuth } = useShell();
  const { user } = useAuth();
  const { t } = useTranslation('home');

  return (
    <div className="home-page">
      <section className="hero-section text-center text-white py-5">
        <div className="container">
          <h1 className="display-4 fw-bold mb-3">{t('hero-title', 'Build Apps with AI')}</h1>
          <p className="lead mb-4">
            {t('hero-subtitle', 'Design, prototype, and generate full-stack applications powered by AI')}
          </p>
          {!user && (
            <Link to="/register" className="btn btn-light btn-lg px-5">
              {t('get-started', 'Get Started')}
            </Link>
          )}
        </div>
      </section>

      {CHAPTERS.map((chapter, index) => (
        <Chapter
          key={chapter.key}
          chapter={chapter}
          reversed={index % 2 === 1}
          shaded={index % 2 === 1}
          t={t}
        />
      ))}

      {!user && (
        <section className="cta-section text-center py-5 text-white">
          <div className="container">
            <h2 className="mb-4">{t('cta-title', 'Ready to Build Your First App?')}</h2>
            <p className="lead mb-4">
              {t('cta-desc', 'Start designing your application with AI-powered tools today.')}
            </p>
            <Link to="/register" className="btn btn-light btn-lg px-5">
              {t('get-started', 'Get Started')}
            </Link>
          </div>
        </section>
      )}
    </div>
  );
};

export default Home;
