# Generated by Django 6.0.4 on 2026-04-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('i18n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('provider', models.CharField(max_length=50)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_cookie_descriptions', to='i18n.translationkey')),
            ],
            options={
                'verbose_name_plural': 'cookies',
            },
        ),
    ]
